plugins {
    id 'java'
    id 'application'
    alias(libs.plugins.shadow)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'org.example.order.lifecycle.flink.job.FillOrderFlinkJob'
}

shadowJar {
    archiveClassifier.set('all')
}

dependencies {
    implementation project(':common')

    implementation libs.flink.core
    implementation libs.flink.streaming.java
    implementation libs.flink.clients
    implementation libs.flink.connector.base
    implementation libs.flink.connector.kafka
    implementation libs.flink.statebackend.forst

    implementation libs.jackson.databind
    implementation libs.jackson.jsr310

    implementation libs.slf4j.api
    runtimeOnly libs.logback.classic

    testImplementation libs.junit.jupiter
}

tasks.named('run', JavaExec) {
    [
            'kafka.bootstrap.servers',
            'kafka.executions.topic',
            'kafka.verification.topic',
            'kafka.commit.offsets.on.checkpoint',
            'flink.offset.reset',
            'flink.group.id',
            'flink.parallelism',
            'flink.print.lifecycle',
            'flink.checkpoint.interval.ms'
    ].each { propertyName ->
        def value = System.getProperty(propertyName)
        if (value != null) {
            systemProperty propertyName, value
        }
    }
}

test {
    useJUnitPlatform()
}